name: Deploy to BigQuery via Cloud Build

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'
      - 'cloudbuild.yaml'

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authorize GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        uses: google-github-actions/cloud-build@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          config: cloudbuild.yaml
