steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        bq query --use_legacy_sql=false --project_id=${PROJECT_ID} < /final_project/data_pipeline/sql/clean_and_transform_data.sql

timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
